language: node_js
node_js: '10'
cache:
  yarn: true
env:
  global:
    - FORCE_COLOR=1
jobs:
  include:
    - stage: test
      install: skip
      script:
        - cd package
        - yarn
        - yarn run prettier-check
        - yarn run build
stages:
  - test
branches:
  only:
    - master
